### ISSUE TITLE
Bug in metalearner.py line 85

### ISSUE THREAD

**Issue by MarkusPfundstein** [maheshkkumar/fscc#1]
Hi guys, 

I think there is an indentation bug in metalearner.py line 85. the call to add the hooks should be within the for loop.

Greetz
M

https://github.com/maheshkkumar/fscc/blob/master/networks/meta_learner.py

**Comment by maheshkkumar** [comment]
Hi, 

Thanks for pointing it out, it must have been a formatting bug and I have fixed it.
