### ISSUE TITLE
Preprocessing on the dataset

### ISSUE THREAD

**Issue by zzpustc** [maheshkkumar/fscc#3]
Hi,

Great application of MAML. I wonder if you haven't released some preprocessing operations. I found I cannot directly run the code, The original dataset has not been divided into 'tasks (classes)', so I will get errors in the get_task.py. 
Hope to hear from you.

Best.

**Comment by maheshkkumar** [comment]
Hi, 

Please refer to #4 for the directory structure to create train and test scenes. We refer to the crowd scenes as either tasks or classes.
