### ISSUE TITLE
The directory structure of the WorldExpo'10 dataset

### ISSUE THREAD

**Issue by Xluo-lc** [maheshkkumar/fscc#4]
I am puzzled if the directory structure of the WorldExpo'10 dataset can be described,especially what directory should groundtruth be in.It takes time to place them correctly to match the code

**Comment by maheshkkumar** [comment]
Hi, 

Here is an overview of the directory structure for the test split containing 5 scenes for WorldExpo'10 dataset. 

```
├─WorldExpo
├──test
├───csvs
├─────104207
├─────200608
├─────200702
├─────202201
├─────500717
├───frames
├─────104207
├─────200608
├─────200702
├─────202201
├─────500717
```
- `csvs`: This directory contains scene-specific density maps for every input image as a `.csv` file.
- `frames`: This directory contains the input RGB images grouped into their respective scenes.

Follow the same setup for the `train` split.

I hope this helps.

**Comment by Xluo-lc** [comment]
Thank you. May I ask how you solve the problem of insufficient memory?I can't use multiple GPUs (nn.DataParallel) directly in you code.
`RuntimeError: CUDA out of memory. Tried to allocate 40.00 MiB (GPU 0; 12.00 GiB total capacity; 10.43 GiB already allocated; 25.12 MiB free; 134.05 MiB cached)`

**Comment by maheshkkumar** [comment]
This version of the code supports training only on a single GPU. However, to make it compatible with multi-GPU training, some functionalities in the dataloader needs to be changed. Since there is no requirement for this now, we do not have plans to update the codebase. Feel free to reopen this, if there are other concerns. Thanks!

**Comment by chenwenhe11** [comment]
Hi, how did you get the WorldExpo'10 dataset? I sent an email to Prof. Xie Rong but never got a reply.
If possible, could you share the download link for the dataset with me, thank you very much!
My email is 476334028@qq.com.

**Comment by LioTxT** [comment]
> This version of the code supports training only on a single GPU. However, to make it compatible with multi-GPU training, some functionalities in the dataloader needs to be changed. Since there is no requirement for this now, we do not have plans to update the codebase. Feel free to reopen this, if there are other concerns. Thanks!

Hi, how did you get the WorldExpo'10 Dataset and if so can you give me the link to download the WorldExpo'10 Dataset? Thank you very much for your help. My e-mail is 1390015317@qq.com.
