### ISSUE TITLE
"The size of tensor a (1024) must match the size of tensor b(128) at non-singleton dimension 3"

### ISSUE THREAD

**Issue by misck** [maheshkkumar/fscc#5]
Hi, When I try to train the project, I find a error as follows:
RuntimeError: "The size of tensor a (1024) must match the size of tensor b(128) at non-singleton dimension 3"

Can you give some solutions? Thank you!

**Comment by misck** [comment]
[](url)
![image](https://user-images.githubusercontent.com/34797664/118244544-3a596100-b4d2-11eb-8d4f-32b2a35850b5.png)

**Comment by maheshkkumar** [comment]
Make sure to have the ground truth and the network prediction to be of the same dimension when computing the RMSE loss. You could solve this by upsampling the predicted density map to match the expected ground-truth dimension. Feel free to reopen this, if there are other concerns.
