### ISSUE TITLE
Pretrained CSRNet

### ISSUE THREAD

**Issue by Viresh-R** [maheshkkumar/fscc#7]
Hey,
By pretrained CSRNet, do you mean Imagenet pretrained Vgg16 layers plus random initialization for rest of the CSRNet layers ? (Looks like the pretrained net is trained on world expo. If that's the case, could you please share the pretrained net as well ? )

Thanks,
Viresh

**Comment by maheshkkumar** [comment]
Hi, 

The pretrained CSRNet here refers to the model trained on the WorldExpo'10 dataset, and we do not have plans for releasing the models. However, the pretrained model can be generated using any of the following implementations.

1. [https://github.com/leeyeehoo/CSRNet-pytorch](https://github.com/leeyeehoo/CSRNet-pytorch)
2. [https://github.com/gjy3035/C-3-Framework](https://github.com/gjy3035/C-3-Framework)

**Comment by Viresh-R** [comment]
Got it. Thanks !
