### ISSUE TITLE
Pretrained model for CSRNet

### ISSUE THREAD

**Issue by Jyerim** [maheshkkumar/fscc#8]
In meta_learner.py, there are # TODO: path of the pre-trained backbone CSRNet. 
In the paper, the model use VGG-16 pretrained model on ImageNet. Does pretrained backbone CSRNet mean the VGG-16 pretrained model on ImageNet?
Can you provide the pretrained model?

**Comment by maheshkkumar** [comment]
1. We train a CSRNet with ImageNet weights on the WorldExpo'10 dataset, referred to as 'baseline pre-trained'.
2. We then use the 'baseline pre-trained' model to initialize our meta-learning setup. The `TODO` refers to this pre-trained CSRNet model, and you can check [CSRNet](https://github.com/leeyeehoo/CSRNet-pytorch) for the architecture details and our paper to train this baseline pre-trained model.

**Comment by Jyerim** [comment]
Thank you

**Comment by Jyerim** [comment]
Thank you so much
