### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by Jyerim** [maheshkkumar/fscc#9]
Could you share the structure of WorldExpo'10 dataset?
I want to know the train, test data file structure.
And Could you provide sample annotation file? I don't know how the annotation file is organized.
If you could share the dataset structure and sample annotation file, it will be very helpful for me.

**Comment by maheshkkumar** [comment]
You can find the structure for the dataset in #4. For the ground-truth annotation file, you can generate the density map using this [script](https://github.com/maheshkkumar/fscc/blob/master/utils/generate_density_maps.py) and the expected input ground-truth for the script is a binary map containing head annotations.

**Comment by Jyerim** [comment]
Thank you so much.

**Comment by weibowei** [comment]
> Could you share the structure of WorldExpo'10 dataset? I want to know the train, test data file structure. And Could you provide sample annotation file? I don't know how the annotation file is organized. If you could share the dataset structure and sample annotation file, it will be very helpful for me.
Hi, how did you get the WorldExpo'10 dataset? I sent an email to Prof. Xie Rong but never got a reply.
If possible, could you share the download link for the dataset with me, thank you very much!
My email is 220191681@seu.edu.cn

**Comment by Jyerim** [comment]
Sorry, i couldn’t get WorldExpo’10 dataset for the same reason. I sent an email to Prof.Xie Rong but didn’t hear back,too.

**Comment by weibowei** [comment]
> Sorry, i couldn’t get WorldExpo’10 dataset for the same reason. I sent an email to Prof.Xie Rong but didn’t hear back,too.

Thanks for your reply.
